### ISSUE TITLE
[BUG] openinyoutube plugin glitch

### ISSUE THREAD

**Issue by BlueStarBRS** [rmkx/Plugins#1]
open in youtube plugin glitches on pop op on people in voice chat locks rly ugly 
![image](https://user-images.githubusercontent.com/25110093/127900675-eb83530e-394c-41ed-86f0-58f6ce003876.png)
![image](https://user-images.githubusercontent.com/25110093/127900995-d181fd56-94bc-4659-8715-815d5ef9e08b.png)

and it glitches on the profile activity tab
![image](https://user-images.githubusercontent.com/25110093/127900873-686901f6-106e-44c0-9ab2-1177935204dd.png)

pls fix looks rly ugly

**Comment by rmkx** [comment]
This is fixed on the last version, save the raw file.
